title: "Yuma<br>Jonathan Sandoval-Castillo"
email: jonathan.sandoval-castillo@flinders.edu.au
description: Senor Research Fellow at MULFU.
description2: Evolution, genomics and scripts.
baseurl: "/" 
url: "" 
twitter_username: Yuma_More
github_username: Yuma248

sass:
  sass_dir: _sass

icon: /assets/img/YumaIcon.png
