title: "Yuma
| Jonathan Sandoval-Castillo"
email: jonathan.sandoval-castillo@flinders.edu.au
description: >- # this means to ignore newlines until "baseurl:"
  I am Yuma a marine biologist diving the vast Coding Ocean, keep finding myself in bug-infested waters, tangled in the tentacles of errors, and scared of killer Java bytes.
baseurl: "/" 
url: "https://Yuma248.github.io/" 
twitter_username: Yuma_More
github_username: Yuma248

sass:
  sass_dir: _sass

icon: /assets/img/icon.jpg
