title: "Yuma"
title2: "Jonathan Sandoval-Castillo"
email: jonathan.sandoval-castillo@flinders.edu.au
description: Senor Research Fellow at MULFU.
description2: Evolution, genomics and scripts.
baseurl: "/" 
url: "" 
twitter_username: Yuma_More
github_username: Yuma248
googlescholar: Xy6VyBcAAAAJ&h
researchgate: Jonathan-Sandoval-Castillo
orcid_id: 0000-0002-8428-3495

sass:
  sass_dir: _sass

icon: /assets/img/YumaIcon.png
