title: "Yuma"
title2: "Jonathan Sandoval-Castillo"
email: jonathan.sandoval-castillo@flinders.edu.au
description: Senor Research Fellow at MULFU.
description2: Evolution, genomics and scripts.
baseurl: "/" 
url: "" 
twitter_username: Yuma_More
github_username: Yuma248
google_scholar: Jonathan Sandoval-Castillo
researchgate: Jonathan Sandoval-Castillo
orcid: 0000-0002-8428-3495
scopus: Jonathan Sandoval-Castillo

sass:
  sass_dir: _sass

icon: /assets/img/YumaIcon.png
